requires:
  archlinux:
    - appstream-glib
    - biblesync
    - cmake
    - dbus-glib
    - docbook-utils
    - enchant
    - git
    - glib2-devel
    - gnome-common
    - gtk3
    - gtkmm
    - intltool
    - libxml2
    - minizip
    - python
    - sword
    - webkit2gtk
    - zip
    # base-devel group (for AUR installs):
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - pacman
    - patch
    - pkgconf
    - sed
    - sudo
    - texinfo
    - which

  debian:
    - appstream-util
    - cmake
    - docbook-utils
    - g++
    - desktop-file-utils
    - fp-utils
    - git
    - gsettings-desktop-schemas-dev
    - intltool
    - itstool
    - libbiblesync-dev
    - libdbus-glib-1-dev
    - libglade2-dev
    - libgail-3-dev
    - libgtk-3-dev
    - libminizip-dev
    - libsoup2.4-dev
    - libsword-dev
    - libwebkit2gtk-4.1-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - python-dev-is-python3
    - swig
    - uuid-dev
    - uuid-runtime
    - yelp-tools
    - xzip  # Needed to build gtkhtml from source
    - zip

  fedora:
    - biblesync-devel
    - cmake
    - dbus-glib-devel
    - desktop-file-utils
    - git
    - docbook-utils
    - gcc-c++
    - gtk3-devel
    - gtkhtml3-devel
    - intltool
    - itstool
    - libappstream-glib-devel
    - libsoup3
    - libuuid-devel
    - libxml2-devel
    - make
    - minizip-devel
    - rpm-build
    - sword-devel
    - webkitgtk4-devel
    - yelp
    - yelp-tools
    - zip

  ubuntu:
    - appstream-util
    - cmake
    - g++
    - desktop-file-utils
    - fp-utils
    - git
    - gsettings-desktop-schemas-dev
    - intltool
    - itstool
    - libbiblesync-dev
    - libdbus-glib-1-dev
    - libgail-3-dev
    - libglade2-dev
    - libgtk-3-dev
    - libminizip-dev
    - libsword-dev
    - libwebkit2gtk-4.1-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - python-dev-is-python3
    - swig
    - uuid-dev
    - uuid-runtime
    - yelp-tools
    - xzip  # Needed to build gtkhtml from source
    - zip

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - |
    START_DIR="$(pwd)"
    WORK_DIR="/dep_build"
    mkdir -p "${WORK_DIR}"
    if [ "${DISTRO_NAME}" == "archlinux" ];then
        cd "${WORK_DIR}"
        id -u aur_install &>/dev/null || useradd -r -m -U -G wheel -k /dev/null aur_install
        install -m600 /dev/stdin /etc/sudoers.d/70-wheel <<< '%wheel ALL=(ALL) ALL'
        install -m600 /dev/stdin /etc/sudoers.d/99-aur_install <<< 'Defaults:aur_install !authenticate'
        curl -o /home/aur_install/aur_install https://raw.githubusercontent.com/gik0geck0/aur_install/master/aur_install.sh
        chmod +x /home/aur_install/aur_install
        aur_install() {
          su -l aur_install -c "./aur_install $1"
        }
        aur_install biblesync
        aur_install gtkhtml4
    fi

build_scripts:
  - |
    set -ex
    export PKG_CONFIG_PATH=/usr/lib/pkgconfig
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DWEBKIT1=ON -DUSE_WEBKIT2=ON .
    make -C build -j$(nproc)
    make -C build mhelp package_source
